// Script data used across multiple sections
export interface Script {
  id: string
  title: string
  description: string
  price: number
  rating: number
  reviews: number
  software: 'ae' | 'pr' | 'dr' | 'blender'
  videoPlaceholder: string
}

export const SOFTWARE_LABELS: Record<string, string> = {
  ae: 'Ae',
  pr: 'Pr',
  dr: 'DR',
  blender: 'Bl',
}

export const SOFTWARE_FULL: Record<string, string> = {
  ae: 'After Effects',
  pr: 'Premiere Pro',
  dr: 'DaVinci Resolve',
  blender: 'Blender',
}

export const SOFTWARE_COLORS: Record<string, string> = {
  ae: '#9999FF',
  pr: '#EA77FF',
  dr: '#FF6B4A',
  blender: '#EA7600',
}

export const SCRIPTS: Script[] = [
  {
    id: 'magic-render',
    title: 'Magic Render',
    description: 'A powerful script to automate and enhance your magic render workflow in seconds.',
    price: 42,
    rating: 4.1,
    reviews: 371,
    software: 'ae',
    videoPlaceholder: '#1b191c',
  },
  {
    id: 'smooth-reframe',
    title: 'Smooth Reframe',
    description: 'A powerful script to automate and enhance your smooth reframe workflow in seconds.',
    price: 42,
    rating: 4.4,
    reviews: 86,
    software: 'dr',
    videoPlaceholder: '#1e1622',
  },
  {
    id: 'pro-glow',
    title: 'Pro Glow',
    description: 'A powerful script to automate and enhance your pro glow workflow in seconds.',
    price: 15,
    rating: 4.9,
    reviews: 469,
    software: 'pr',
    videoPlaceholder: '#201521',
  },
  {
    id: 'pro-nodes',
    title: 'Pro Nodes',
    description: 'A powerful script to automate and enhance your pro nodes workflow in seconds.',
    price: 41,
    rating: 4.1,
    reviews: 492,
    software: 'ae',
    videoPlaceholder: '#1b1625',
  },
  {
    id: 'fast-render',
    title: 'Fast Render',
    description: 'A powerful script to automate and enhance your fast render workflow in seconds.',
    price: 52,
    rating: 4.8,
    reviews: 229,
    software: 'pr',
    videoPlaceholder: '#1a2616',
  },
  {
    id: 'smooth-color-match',
    title: 'Smooth Color Match',
    description: 'A powerful script to automate and enhance your smooth color match workflow in seconds.',
    price: 40,
    rating: 4.0,
    reviews: 361,
    software: 'pr',
    videoPlaceholder: '#1e2518',
  },
  {
    id: 'hyper-glow',
    title: 'Hyper Glow',
    description: 'A powerful script to automate and enhance your hyper glow workflow in seconds.',
    price: 58,
    rating: 4.8,
    reviews: 239,
    software: 'pr',
    videoPlaceholder: '#172128',
  },
  {
    id: 'pro-color-match',
    title: 'Pro Color Match',
    description: 'A powerful script to automate and enhance your pro color match workflow in seconds.',
    price: 60,
    rating: 4.9,
    reviews: 357,
    software: 'blender',
    videoPlaceholder: '#261428',
  },
  {
    id: 'clean-captions',
    title: 'Clean Captions',
    description: 'A powerful script to automate and enhance your clean captions workflow in seconds.',
    price: 25,
    rating: 4.5,
    reviews: 116,
    software: 'pr',
    videoPlaceholder: '#232020',
  },
  {
    id: 'super-rig',
    title: 'Super Rig',
    description: 'A powerful script to automate and enhance your super rig workflow in seconds.',
    price: 60,
    rating: 4.4,
    reviews: 146,
    software: 'blender',
    videoPlaceholder: '#251415',
  },
  {
    id: 'magic-distort',
    title: 'Magic Distort',
    description: 'A powerful script to automate and enhance your magic distort workflow in seconds.',
    price: 37,
    rating: 4.7,
    reviews: 182,
    software: 'blender',
    videoPlaceholder: '#1f1b28',
  },
  {
    id: 'hyper-color-match',
    title: 'Hyper Color Match',
    description: 'A powerful script to automate and enhance your hyper color match workflow in seconds.',
    price: 16,
    rating: 4.6,
    reviews: 283,
    software: 'pr',
    videoPlaceholder: '#1e2028',
  },
  {
    id: 'super-align',
    title: 'Super Align',
    description: 'A powerful script to automate and enhance your super align workflow in seconds.',
    price: 60,
    rating: 4.5,
    reviews: 210,
    software: 'dr',
    videoPlaceholder: '#1a1c1e',
  },
  {
    id: 'quick-sync',
    title: 'Quick Sync',
    description: 'A powerful script to automate and enhance your quick sync workflow in seconds.',
    price: 53,
    rating: 5.0,
    reviews: 96,
    software: 'pr',
    videoPlaceholder: '#14271f',
  },
  {
    id: 'quick-captions',
    title: 'Quick Captions',
    description: 'A powerful script to automate and enhance your quick captions workflow in seconds.',
    price: 45,
    rating: 4.4,
    reviews: 459,
    software: 'ae',
    videoPlaceholder: '#192020',
  },
  {
    id: 'clean-keyer',
    title: 'Clean Keyer',
    description: 'A powerful script to automate and enhance your clean keyer workflow in seconds.',
    price: 50,
    rating: 4.1,
    reviews: 176,
    software: 'ae',
    videoPlaceholder: '#211d1a',
  },
  {
    id: 'hyper-align',
    title: 'Hyper Align',
    description: 'A powerful script to automate and enhance your hyper align workflow in seconds.',
    price: 40,
    rating: 4.1,
    reviews: 388,
    software: 'blender',
    videoPlaceholder: '#181628',
  },
  {
    id: 'ultra-tracker',
    title: 'Ultra Tracker',
    description: 'A powerful script to automate and enhance your ultra tracker workflow in seconds.',
    price: 23,
    rating: 4.4,
    reviews: 176,
    software: 'blender',
    videoPlaceholder: '#1e2018',
  },
  {
    id: 'clean-render',
    title: 'Clean Render',
    description: 'A powerful script to automate and enhance your clean render workflow in seconds.',
    price: 53,
    rating: 4.4,
    reviews: 463,
    software: 'blender',
    videoPlaceholder: '#23231d',
  },
  {
    id: 'hyper-render',
    title: 'Hyper Render',
    description: 'A powerful script to automate and enhance your hyper render workflow in seconds.',
    price: 53,
    rating: 4.3,
    reviews: 293,
    software: 'blender',
    videoPlaceholder: '#191916',
  },
  {
    id: 'batch-sync',
    title: 'Batch Sync',
    description: 'A powerful script to automate and enhance your batch sync workflow in seconds.',
    price: 61,
    rating: 4.9,
    reviews: 283,
    software: 'blender',
    videoPlaceholder: '#181a26',
  },
  {
    id: 'super-keyer',
    title: 'Super Keyer',
    description: 'A powerful script to automate and enhance your super keyer workflow in seconds.',
    price: 63,
    rating: 4.1,
    reviews: 412,
    software: 'ae',
    videoPlaceholder: '#231922',
  },
  {
    id: 'hyper-captions',
    title: 'Hyper Captions',
    description: 'A powerful script to automate and enhance your hyper captions workflow in seconds.',
    price: 36,
    rating: 4.7,
    reviews: 16,
    software: 'dr',
    videoPlaceholder: '#25151b',
  },
  {
    id: 'clean-distort',
    title: 'Clean Distort',
    description: 'A powerful script to automate and enhance your clean distort workflow in seconds.',
    price: 56,
    rating: 4.4,
    reviews: 292,
    software: 'ae',
    videoPlaceholder: '#282816',
  },
  {
    id: 'smooth-nodes',
    title: 'Smooth Nodes',
    description: 'A powerful script to automate and enhance your smooth nodes workflow in seconds.',
    price: 37,
    rating: 4.6,
    reviews: 290,
    software: 'dr',
    videoPlaceholder: '#22181c',
  },
  {
    id: 'super-reframe',
    title: 'Super Reframe',
    description: 'A powerful script to automate and enhance your super reframe workflow in seconds.',
    price: 37,
    rating: 4.9,
    reviews: 283,
    software: 'dr',
    videoPlaceholder: '#1a1d16',
  },
  {
    id: 'fast-titles',
    title: 'Fast Titles',
    description: 'A powerful script to automate and enhance your fast titles workflow in seconds.',
    price: 32,
    rating: 4.0,
    reviews: 358,
    software: 'dr',
    videoPlaceholder: '#1a1e25',
  },
  {
    id: 'ultra-distort-9',
    title: 'Ultra Distort 9',
    description: 'A powerful script to automate and enhance your ultra distort 9 workflow in seconds.',
    price: 51,
    rating: 4.7,
    reviews: 172,
    software: 'ae',
    videoPlaceholder: '#1f151f',
  },
  {
    id: 'easy-rig',
    title: 'Easy Rig',
    description: 'A powerful script to automate and enhance your easy rig workflow in seconds.',
    price: 22,
    rating: 5.0,
    reviews: 87,
    software: 'ae',
    videoPlaceholder: '#1c1616',
  },
  {
    id: 'auto-reframe',
    title: 'Auto Reframe',
    description: 'A powerful script to automate and enhance your auto reframe workflow in seconds.',
    price: 59,
    rating: 4.8,
    reviews: 190,
    software: 'dr',
    videoPlaceholder: '#1c281a',
  },
  {
    id: 'smart-glow',
    title: 'Smart Glow',
    description: 'A powerful script to automate and enhance your smart glow workflow in seconds.',
    price: 47,
    rating: 4.5,
    reviews: 266,
    software: 'pr',
    videoPlaceholder: '#1c2625',
  },
  {
    id: 'hyper-exporter',
    title: 'Hyper Exporter',
    description: 'A powerful script to automate and enhance your hyper exporter workflow in seconds.',
    price: 36,
    rating: 4.5,
    reviews: 270,
    software: 'dr',
    videoPlaceholder: '#17211a',
  },
  {
    id: 'smooth-glow-6',
    title: 'Smooth Glow 6',
    description: 'A powerful script to automate and enhance your smooth glow 6 workflow in seconds.',
    price: 32,
    rating: 4.3,
    reviews: 277,
    software: 'dr',
    videoPlaceholder: '#22251b',
  },
  {
    id: 'batch-titles-5',
    title: 'Batch Titles 5',
    description: 'A powerful script to automate and enhance your batch titles 5 workflow in seconds.',
    price: 39,
    rating: 4.8,
    reviews: 409,
    software: 'blender',
    videoPlaceholder: '#1d2817',
  },
  {
    id: 'magic-captions',
    title: 'Magic Captions',
    description: 'A powerful script to automate and enhance your magic captions workflow in seconds.',
    price: 34,
    rating: 4.7,
    reviews: 12,
    software: 'dr',
    videoPlaceholder: '#192118',
  },
  {
    id: 'easy-titles',
    title: 'Easy Titles',
    description: 'A powerful script to automate and enhance your easy titles workflow in seconds.',
    price: 62,
    rating: 4.2,
    reviews: 187,
    software: 'dr',
    videoPlaceholder: '#241523',
  },
  {
    id: 'smart-mask',
    title: 'Smart Mask',
    description: 'A powerful script to automate and enhance your smart mask workflow in seconds.',
    price: 16,
    rating: 4.2,
    reviews: 492,
    software: 'ae',
    videoPlaceholder: '#272122',
  },
  {
    id: 'easy-align',
    title: 'Easy Align',
    description: 'A powerful script to automate and enhance your easy align workflow in seconds.',
    price: 19,
    rating: 4.8,
    reviews: 12,
    software: 'blender',
    videoPlaceholder: '#251f1c',
  },
  {
    id: 'auto-keyer',
    title: 'Auto Keyer',
    description: 'A powerful script to automate and enhance your auto keyer workflow in seconds.',
    price: 40,
    rating: 4.0,
    reviews: 322,
    software: 'ae',
    videoPlaceholder: '#18211b',
  },
  {
    id: 'smooth-rig',
    title: 'Smooth Rig',
    description: 'A powerful script to automate and enhance your smooth rig workflow in seconds.',
    price: 29,
    rating: 4.8,
    reviews: 162,
    software: 'blender',
    videoPlaceholder: '#211e1b',
  },
  {
    id: 'batch-tracker',
    title: 'Batch Tracker',
    description: 'A powerful script to automate and enhance your batch tracker workflow in seconds.',
    price: 56,
    rating: 4.8,
    reviews: 459,
    software: 'dr',
    videoPlaceholder: '#1c151b',
  },
  {
    id: 'auto-titles-3',
    title: 'Auto Titles 3',
    description: 'A powerful script to automate and enhance your auto titles 3 workflow in seconds.',
    price: 18,
    rating: 4.7,
    reviews: 369,
    software: 'pr',
    videoPlaceholder: '#171a24',
  },
  {
    id: 'ultra-distort',
    title: 'Ultra Distort',
    description: 'A powerful script to automate and enhance your ultra distort workflow in seconds.',
    price: 18,
    rating: 4.7,
    reviews: 145,
    software: 'blender',
    videoPlaceholder: '#1b161e',
  },
  {
    id: 'fast-nodes',
    title: 'Fast Nodes',
    description: 'A powerful script to automate and enhance your fast nodes workflow in seconds.',
    price: 63,
    rating: 4.5,
    reviews: 125,
    software: 'blender',
    videoPlaceholder: '#172815',
  },
  {
    id: 'auto-captions-1',
    title: 'Auto Captions 1',
    description: 'A powerful script to automate and enhance your auto captions 1 workflow in seconds.',
    price: 35,
    rating: 4.1,
    reviews: 93,
    software: 'dr',
    videoPlaceholder: '#1b1822',
  },
  {
    id: 'ultra-reframe',
    title: 'Ultra Reframe',
    description: 'A powerful script to automate and enhance your ultra reframe workflow in seconds.',
    price: 57,
    rating: 4.2,
    reviews: 262,
    software: 'ae',
    videoPlaceholder: '#232421',
  },
  {
    id: 'easy-exporter-2',
    title: 'Easy Exporter 2',
    description: 'A powerful script to automate and enhance your easy exporter 2 workflow in seconds.',
    price: 54,
    rating: 4.1,
    reviews: 349,
    software: 'ae',
    videoPlaceholder: '#141521',
  },
  {
    id: 'fast-align-4',
    title: 'Fast Align 4',
    description: 'A powerful script to automate and enhance your fast align 4 workflow in seconds.',
    price: 47,
    rating: 4.4,
    reviews: 144,
    software: 'dr',
    videoPlaceholder: '#252125',
  },
  {
    id: 'ultra-render',
    title: 'Ultra Render',
    description: 'A powerful script to automate and enhance your ultra render workflow in seconds.',
    price: 39,
    rating: 4.5,
    reviews: 296,
    software: 'blender',
    videoPlaceholder: '#19141f',
  },
  {
    id: 'pro-keyer',
    title: 'Pro Keyer',
    description: 'A powerful script to automate and enhance your pro keyer workflow in seconds.',
    price: 63,
    rating: 4.5,
    reviews: 424,
    software: 'dr',
    videoPlaceholder: '#231d26',
  },
]

export const TESTIMONIALS = [
  {
    name: 'Sarah Chen',
    role: 'Senior Editor',
    studio: 'Framehaus',
    software: 'ae',
    quote: 'Kinetic Captions alone saved our team 6 hours on a 30-episode series. The scripts just work.',
  },
  {
    name: 'Marcus Obi',
    role: 'Motion Designer',
    studio: 'Optik Studio',
    software: 'ae',
    quote: "I've tried every AE script marketplace. ScriptFilers is the only one where every single tool feels production-ready.",
  },
  {
    name: 'Lina Park',
    role: 'Colorist',
    studio: 'PostWorks',
    software: 'dr',
    quote: 'Node Automator changed how I approach complex grades. What took 20 minutes now takes one click.',
  },
  {
    name: 'James Whitfield',
    role: 'Lead Editor',
    studio: 'Cutline Media',
    software: 'pr',
    quote: 'Auto Reframe Pro handles 90% of our social deliverables. Genuinely indispensable.',
  },
  {
    name: 'Anya Kowalski',
    role: '3D Artist',
    studio: 'Polygon Collective',
    software: 'blender',
    quote: 'Quick Rig Pro does in seconds what used to eat an entire afternoon. Magic.',
  },
  {
    name: 'David Morales',
    role: 'VFX Supervisor',
    studio: 'Ember Post',
    software: 'ae',
    quote: "Motion Trails FX is the kind of tool that makes clients think you're a wizard. Worth every cent.",
  },
  {
    name: 'Priya Nair',
    role: 'Freelance Editor',
    studio: 'Independent',
    software: 'pr',
    quote: 'The batch color matching is absurdly good. Handles mixed footage from three cameras without a hitch.',
  },
  {
    name: 'Tom Eriksson',
    role: 'Creative Director',
    studio: 'Nordic Frame',
    software: 'ae',
    quote: "We've standardized on ScriptFilers across the studio. Consistent quality, amazing support.",
  },
]

export const FAQ_ITEMS = [
  {
    question: 'What license do I get with a single script purchase?',
    answer: 'Every single-script purchase includes a lifetime license for one user. You can use it on up to two machines (e.g. desktop and laptop). Updates are free forever — no annual renewal, no expiration.',
  },
  {
    question: 'Which software versions are supported?',
    answer: 'We support the two most recent major versions of each application. For After Effects and Premiere Pro, that currently means 2024 and 2025. DaVinci Resolve 18+ and Blender 3.6+ are supported. When a new version drops, we update within two weeks.',
  },
  {
    question: 'Do I need any coding knowledge to use these scripts?',
    answer: "Not at all. Every script is a single file — drop it into your application's scripts folder, restart, and it appears in your menu or as a panel. No command line, no dependencies, no configuration.",
  },
  {
    question: 'What is your refund policy?',
    answer: "We offer a 14-day money-back guarantee, no questions asked. If a script doesn't work as described, or it's simply not what you expected, email us and we'll process a full refund within 24 hours.",
  },
  {
    question: 'What does the Studio License include?',
    answer: 'The Studio License gives your team access to every script across all four supported applications — After Effects, Premiere Pro, DaVinci Resolve, and Blender. It includes 5 seats (expandable), priority support, and early access to new scripts before public release.',
  },
  {
    question: 'Can I use scripts in commercial/client projects?',
    answer: 'Yes. All licenses — single, bundle, and studio — include full commercial usage rights. Use them in client work, broadcast, film, YouTube, advertising — whatever you need.',
  },
]
